{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.paranoid-wifi;

  # Default sensitive ports to block on untrusted networks
  # Format: "port/proto" (e.g., "22/tcp" for SSH)
  defaultBlockedPorts = [
    "22/tcp"    # SSH
    "139/tcp"   # SMB NetBIOS
    "445/tcp"   # SMB
    "2049/tcp"  # NFS
    "3389/tcp"  # RDP
    "5900/tcp"  # VNC
    "5901/tcp"  # VNC alternate
    "631/tcp"   # CUPS (printing)
    "631/udp"   # CUPS
    "9100/tcp"  # Printer
  ];

  # Generate the dispatcher script
  dispatcherScript = pkgs.writeScript "paranoid-wifi-dispatcher" ''
    #!${pkgs.bash}/bin/bash

    # NetworkManager dispatcher script to block sensitive ports on untrusted WiFi
    # Generated by NixOS paranoid-wifi module

    # Get the actual interface name
    INTERFACE=$1

    HOME_WIFI_SSIDS=(${concatStringsSep " " cfg.home-wifi})
    LOG_FILE="/var/log/paranoid-wifi.log"
    CHAINS_PREFIX="paranoid-wifi"

    # Only run when interface comes up
    [ "$2" != "up" ] && exit 0

    # Check if this interface is WiFi and get connection name
    CONN_INFO=$(${pkgs.networkmanager}/bin/nmcli -t -f DEVICE,TYPE,CONNECTION device status 2>/dev/null | ${pkgs.gawk}/bin/awk -F: -v iface="$INTERFACE" '$1==iface {print $2":"$3}')

    # Skip if not WiFi or not connected
    [[ "$CONN_INFO" != wifi:* ]] && exit 0

    # Get SSID from connection
    CONNECTION_NAME=''${CONN_INFO#*:}
    CURRENT_SSID=$(${pkgs.networkmanager}/bin/nmcli -t -f 802-11-wireless.ssid connection show "$CONNECTION_NAME" 2>/dev/null | ${pkgs.gawk}/bin/awk -F: '$1=="802-11-wireless.ssid" {print $2}')

    log() {
        echo "[$(date)] $1" >> "$LOG_FILE"
    }

    # Skip if not connected to WiFi (no SSID = not WiFi)
    if [ -z "$CURRENT_SSID" ]; then
        exit 0
    fi

    # Check if current SSID is in the list of home WiFi SSIDs
    is_home_wifi=false
    for ssid in "''${HOME_WIFI_SSIDS[@]}"; do
        if [ "$CURRENT_SSID" = "$ssid" ]; then
            is_home_wifi=true
            break
        fi
    done

    # On home WiFi, remove paranoid rules for this interface only
    if $is_home_wifi; then
        log "On home WiFi ($CURRENT_SSID), removing paranoid rules for: $INTERFACE"
        # Delete all paranoid-wifi rules for this specific interface
        while true; do
            handle=$(${pkgs.nftables}/bin/nft -a list chain inet filter input 2>/dev/null | ${pkgs.gnugrep}/bin/grep "iifname \"$INTERFACE\".*$CHAINS_PREFIX" | ${pkgs.gawk}/bin/awk '{print $NF}' | head -1)
            [ -z "$handle" ] && break
            ${pkgs.nftables}/bin/nft delete rule inet filter input handle "$handle" 2>/dev/null
        done
        exit 0
    fi

    # On untrusted WiFi, block sensitive ports
    log "On untrusted WiFi ($CURRENT_SSID), blocking ports for: $INTERFACE"

    # Build nftables rules for each blocked port
    ${concatMapStringsSep "\n" (port: ''
      ${pkgs.nftables}/bin/nft insert rule inet filter input iifname "$INTERFACE" meta l4proto { ${elemAt (splitString "/" port) 1} } th dport ${elemAt (splitString "/" port) 0} counter drop comment "$CHAINS_PREFIX-${port}"
    '') cfg.blocked-ports}

    log "Paranoid firewall rules applied"
  '';

in {
  options.paranoid-wifi = {
    enable = mkEnableOption "Paranoid WiFi - block sensitive ports on untrusted networks";

    home-wifi = mkOption {
      type = types.listOf types.str;
      example = [ "MyHomeWiFi" "MyPhoneHotspot" ];
      description = "List of trusted home WiFi SSIDs where ports should NOT be blocked";
    };

    blocked-ports = mkOption {
      type = types.listOf types.str;
      default = defaultBlockedPorts;
      example = [ "22/tcp" "445/tcp" "3306/tcp" ];
      description = "List of ports to block on untrusted WiFi (format: port/proto)";
    };
  };

  config = mkIf cfg.enable {
    # Enable nftables (required for dynamic rules)
    networking.nftables.enable = true;

    # Ensure NetworkManager is enabled
    networking.networkmanager.enable = mkDefault true;

    # Add the dispatcher script
    environment.etc."NetworkManager/dispatcher.d/98-paranoid-wifi.sh" = {
      source = dispatcherScript;
      mode = "0755";
    };

    # Ensure NetworkManager-dispatcher service is enabled
    systemd.services.NetworkManager-dispatcher = {
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Restart = "on-failure";
        RestartSec = "5s";
      };
    };
  };
}
