{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.wg-auto;

  # Generate the dispatcher script based on configuration
  dispatcherScript = pkgs.writeScript "wg-auto-dispatcher" ''
    #!${pkgs.bash}/bin/bash

    # NetworkManager dispatcher script to auto-connect WireGuard VPN on home WiFi
    # Generated by NixOS wg-auto module

    VPN_NAME="${cfg.wg-name}"
    HOME_WIFI_SSIDS=(${concatStringsSep " " cfg.home-wifi})
    LOG_FILE="/var/log/wg-auto.log"


    # Only run when interface comes up
    [ "$2" != "up" ] && exit 0

    # Disconnect first
    ${pkgs.networkmanager}/bin/nmcli connection down "$VPN_NAME" 2>&1 | tee -a "$LOG_FILE"

    # Get current connection SSID
    CURRENT_SSID=$(${pkgs.networkmanager}/bin/nmcli -t -f active,ssid dev wifi | ${pkgs.gawk}/bin/awk -F: '$1=="yes" {print $2}')

    log() {
        echo "[$(date)] $1" >> "$LOG_FILE"
    }

    # Wait for internet connectivity (including DNS resolution) before proceeding
    wait_for_internet() {
        local attempt=0
        local wait_time=2

        log "Waiting for internet connectivity..."

        while true; do
            # Ping kernel.org to test both connectivity and DNS resolution
            if ${pkgs.iputils}/bin/ping -c 1 -W 2 kernel.org >/dev/null 2>&1; then
                log "Internet connectivity confirmed (DNS resolving)"
                return 0
            fi

            attempt=$((attempt + 1))
            log "Internet not ready yet (attempt $attempt), retrying in ''${wait_time}s..."
            sleep $wait_time
        done
    }


    # Check if current SSID is in the list of home WiFi SSIDs
    is_home_wifi=false
    for ssid in "''${HOME_WIFI_SSIDS[@]}"; do
        if [ "$CURRENT_SSID" = "$ssid" ]; then
            is_home_wifi=true
            break
        fi
    done

    if $is_home_wifi; then
        # wifi is disconnected already
        exit 0
    fi

    wait_for_internet()
    ${pkgs.networkmanager}/bin/nmcli connection up "$VPN_NAME" 2>&1 | tee -a "$LOG_FILE"
  '';

in {
  options.wg-auto = {
    enable = mkEnableOption "WireGuard auto-connect";

    home-wifi = mkOption {
      type = types.listOf types.str;
      example = [ "tiktok" "tiktok-portable" ];
      description =
        "List of home WiFi SSIDs that should trigger VPN connection";
    };

    wg-name = mkOption {
      type = types.str;
      example = "advan";
      description = "Name of the WireGuard VPN connection to manage";
    };
  };

  config = mkIf cfg.enable {
    # Ensure NetworkManager is enabled
    networking.networkmanager.enable = mkDefault true;

    # Add the dispatcher script
    environment.etc."NetworkManager/dispatcher.d/99-wg-auto.sh" = {
      source = dispatcherScript;
      mode = "0755";
    };

    # Ensure NetworkManager-dispatcher service is enabled
    systemd.services.NetworkManager-dispatcher = {
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Restart = "on-failure";
        RestartSec = "5s";
      };
    };
  };
}
