{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.wg-auto;

  # Generate the dispatcher script based on configuration
  dispatcherScript = pkgs.writeScript "wg-auto-dispatcher" ''
    #!${pkgs.bash}/bin/bash

    # NetworkManager dispatcher script to auto-connect WireGuard VPN on home WiFi
    # Generated by NixOS wg-auto module

      VPN_NAME="${cfg.wg-name}"
      HOME_WIFI_SSIDS=(${concatStringsSep " " cfg.home-wifi})
      LOG_FILE="/var/log/wg-auto.log"

      # Only run when interface comes up
      [ "$2" != "up" ] && exit 0

      # Get current connection SSID
      CURRENT_SSID=$(${pkgs.networkmanager}/bin/nmcli -t -f active,ssid dev wifi | ${pkgs.gawk}/bin/awk -F: '$1=="yes" {print $2}')

      log() {
          echo "[$(date)] $1" >> "$LOG_FILE"
      }

      # Check if current SSID is in the list of home WiFi SSIDs
      is_home_wifi=false
      for ssid in "''${HOME_WIFI_SSIDS[@]}"; do
          if [ "$CURRENT_SSID" = "$ssid" ]; then
              is_home_wifi=true
              break
          fi
      done

      # Check if VPN is already connected
      VPN_CONNECTED=$(${pkgs.networkmanager}/bin/nmcli connection show --active | grep -q "^$VPN_NAME " && echo "true" || echo "false")

      if $is_home_wifi; then
          # Disconnect VPN if on home WiFi
          if [ "$VPN_CONNECTED" = "true" ]; then
              log "On home WiFi ($CURRENT_SSID), disconnecting VPN: $VPN_NAME..."
              ${pkgs.networkmanager}/bin/nmcli connection down "$VPN_NAME" 2>&1 | tee -a "$LOG_FILE"
          else
              log "On home WiFi ($CURRENT_SSID), VPN already disconnected"
          fi
          # Exit early for home WiFi case
          exit 0
      fi

      # Not on home WiFi - connect VPN if needed
      if [ "$VPN_CONNECTED" = "false" ]; then
          log "Not on home WiFi (current: $CURRENT_SSID), connecting VPN: $VPN_NAME..."
          ${pkgs.networkmanager}/bin/nmcli connection up "$VPN_NAME" 2>&1 | tee -a "$LOG_FILE"
      else
          log "VPN $VPN_NAME already connected"
      fi
  '';

in {
  options.wg-auto = {
    enable = mkEnableOption "WireGuard auto-connect";

    home-wifi = mkOption {
      type = types.listOf types.str;
      example = [ "tiktok" "tiktok-portable" ];
      description = "List of home WiFi SSIDs that should trigger VPN connection";
    };

    wg-name = mkOption {
      type = types.str;
      example = "advan";
      description = "Name of the WireGuard VPN connection to manage";
    };
  };

  config = mkIf cfg.enable {
    # Ensure NetworkManager is enabled
    networking.networkmanager.enable = mkDefault true;

    # Add the dispatcher script
    environment.etc."NetworkManager/dispatcher.d/99-wg-auto.sh" = {
      source = dispatcherScript;
      mode = "0755";
    };

    # Ensure NetworkManager-dispatcher service is enabled
    systemd.services.NetworkManager-dispatcher = {
      wantedBy = [ "multi-user.target" ];
      serviceConfig = {
        Restart = "on-failure";
        RestartSec = "5s";
      };
    };
  };
}
